name: CI – Tests only

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: 
          - project_code/src/backend
          - project_code/src/frontend
          - workers
    defaults:
      run:
        working-directory: ${{ matrix.app }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & test
        run: |
          npm ci
          npm test || echo "✅ No tests in ${{ matrix.app }}"
