name: CI – Tests & Coverage (Matrix)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        app: [project_code/src/backend, project_code/src/frontend, workers]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ${{ matrix.app }}
        run: npm install

      - name: Run tests
        working-directory: ${{ matrix.app }}
        run: npm run test

      - name: Upload coverage report for ${{ matrix.app }}
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: coverage-report-${{ matrix.app }}
          path: ${{ matrix.app }}/coverage/lcov.info
          if-no-files-found: warn

