name: CI – Tests & Coverage (Matrix)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [backend, frontend, workers]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change to ${{ matrix.app }} directory
        run: cd ${{ matrix.app }}

      - name: Install dependencies
        run: |
          cd ${{ matrix.app }}
          npm install

      - name: Run tests
        run: |
          cd ${{ matrix.app }}
          npm run test || echo "⚠️ No test script defined"

      - name: Upload coverage report if exists
        if: ${{ hashFiles('coverage/lcov.info') != '' }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/lcov.info

