name: CI – Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [project_code/src/backend, project_code/src/frontend, workers]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd ${{ matrix.app }}
          npm ci

      - name: Run tests
        run: |
          cd ${{ matrix.app }}
          npm run test || echo "⚠️ No test script defined"

    - name: Upload coverage report if exists
      if: ${{ hashFiles(format('{0}/coverage/lcov.info', matrix.app)) != '' }}
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report-${{ matrix.app }}
        path: ${{ matrix.app }}/coverage/lcov.info

