name: CI – Tests & Coverage (Matrix)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [backend, frontend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Use project ${{ matrix.app }}
        run: cd ${{ matrix.app }}

      - name: Restore dependencies from cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ matrix.app }}/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/package-lock.json', matrix.app)) }}

      - name: Install dependencies
        run: |
          cd ${{ matrix.app }}
          npm install

      - name: Run tests
        run: |
          cd ${{ matrix.app }}
          npm run test

      - name: Run coverage
        run: |
          cd ${{ matrix.app }}
          npm run test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.app }}-coverage
          path: ${{ matrix.app }}/coverage
